services:
  express:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: blog
    env_file:
      - .env
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "3001:3001"
    networks:
      - net
    depends_on:
      mysql-blog:
        condition: service_healthy

  mysql-blog:
    image: mysql:8.0
    container_name: mysql-blog
    environment:
      MYSQL_DATABASE: blog
      MYSQL_USER: blog_user
      MYSQL_PASSWORD: blog_password
      MYSQL_ROOT_PASSWORD: pwroot
    volumes:
      - ./mysql-volume:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-ppwroot"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

networks:
  net:
    driver: bridge

volumes:
  node_modules:
  mysql_data:
